# -*- coding: utf-8 -*-
"""Le 49 abilità ufficiali (SRD 2024 di poke5e.app) che servono alle specie aggiunte.
Nome italiano dei giochi (PokéAPI), testo tradotto dal sistema."""
NEFASTO = ("Le creature entro 18 m da questo Pokémon che non hanno un'abilità «Nefasta/o» hanno −4 a %s "
           "(minimo 1). L'effetto non si cumula e svanisce quando la creatura esce dall'area.")
VENTO = ("Aerocolpo, Bora, Fendivento, Ondacalda, Raffica, Ruggito, Tempesta Ardente, Tempesta Boreale, Tempesta Amorosa, "
         "Tempesta Tonante, Tifone, Tornado, Turbosabbia, Ventagliente, Ventofatato, Ventogelato, Ventoincoda, Vortipetalo")
ABIL = {
 'anger-shell': ('Iraguscio', "Quando i PF scendono sotto la metà del massimo, la CA cala di 2 ma FOR e DES aumentano di 2 ciascuna (massimo 22). Dopo un riposo lungo CA, FOR e DES tornano com'erano."),
 'armor-tail': ('Codarmatura', "Finché questo Pokémon è in campo, i Pokémon ostili che vede non possono usare mosse che richiedono un'azione bonus."),
 'as-one': ('Unità Equina', "Gli avversari in lotta con questo Pokémon non possono mangiare le bacche che tengono. Quando manda KO un avversario, può subito muoversi fino a 6 m e compiere un'altra azione. Questa abilità non può essere scambiata."),
 'beads-of-ruin': ('Monile Nefasto', NEFASTO % 'Carisma'),
 'commander': ('Torre di Comando', "Una volta per riposo lungo, con un'azione questo Pokémon può saltare nella bocca di un Dondozo vicino. Lì dentro non può compiere azioni che bersaglino creature o oggetti fuori dal corpo di Dondozo, e non può essere bersagliato; Dondozo diventa competente nei TS su SAG. Esce con un'azione, o viene sputato in uno spazio adiacente se Dondozo va KO."),
 'costar': ('Coprotagonismo', "Quando è entro 1,5 m da un alleato, questo Pokémon ha vantaggio ai tiri per colpire."),
 'cud-chew': ('Ruminante', "Dopo aver mangiato una bacca, nel turno successivo questo Pokémon può consumarla una seconda volta; poi è finita per davvero."),
 'dauntless-shield': ('Scudo Saldo', "Gli attacchi in mischia contro questo Pokémon hanno svantaggio."),
 'desolate-land': ('Terra Estrema', "Finché questo Pokémon è in lotta, il tempo è Sole Estremo e non può cambiare: come il sole intenso, ma i danni di tipo Acqua sono annullati. Se è attivo anche Mare Primordiale, il tempo è insieme Sole Estremo e Pioggia Battente."),
 'earth-eater': ('Mangiaterra', "Questo Pokémon non subisce danni dagli attacchi di tipo Terra: ne assorbe invece la metà, recuperando PF."),
 'electromorphosis': ('Convertivolt', "Quando questo Pokémon subisce danni, può raddoppiare il modificatore MOSSA ai danni della sua prossima mossa di tipo Elettro."),
 'embody-aspect-cornerstone': ('Incarnazione (Fondamenta)', "Questo Pokémon ottiene l'abilità quando si teracristallizza: la sua COS diventa 23, se non è già più alta."),
 'embody-aspect-heartflame': ('Incarnazione (Focolare)', "Questo Pokémon ottiene l'abilità quando si teracristallizza: la sua FOR diventa 23, se non è già più alta."),
 'embody-aspect-teal': ('Incarnazione (Turchese)', "Questo Pokémon ottiene l'abilità quando si teracristallizza: la sua DES diventa 23, se non è già più alta."),
 'embody-aspect-wellspring': ('Incarnazione (Pozzo)', "Questo Pokémon ottiene l'abilità quando si teracristallizza: il suo CAR diventa 23, se non è già più alto."),
 'good-as-gold': ('Corpo Aureo', "Questo Pokémon è immune agli stati alterati."),
 'guard-dog': ('Cane da Guardia', "Questo Pokémon non può essere costretto a uscire dalla lotta da altre mosse. Le prove di Intimidire contro di lui hanno svantaggio, e l'abilità Prepotenza non ha effetto su di lui."),
 'hadron-engine': ('Motore Adronico', "Con un'azione bonus questo Pokémon trasforma il terreno in Campo Elettrico per 5 round, due volte per riposo breve. Sul Campo Elettrico ha vantaggio ai tiri per colpire con DES o SAG come potenza."),
 'hospitality': ('Ospitalità', "All'inizio del suo turno, tutti gli alleati entro 6 m da questo Pokémon ottengono 1d4 PF temporanei, che sostituiscono quelli che avevano."),
 'intrepid-sword': ('Spada Indomita', "Questo Pokémon attacca in mischia con vantaggio."),
 'lingering-aroma': ('Odore Tenace', "Quando questo Pokémon colpisce o viene colpito in mischia, un'abilità a caso dell'altro diventa Odore Tenace fino alla fine dello scontro o finché non viene richiamato."),
 'minds-eye': ('Occhio Interiore', "Le mosse di tipo Normale e Lotta di questo Pokémon ignorano le immunità. Ignora anche lo svantaggio agli attacchi contro bersagli che vede."),
 'mycelium-might': ('Micoforza', "Una volta per riposo breve, quando costringe una creatura a un tiro salvezza che infligge uno stato alterato, questo Pokémon può farle tirare con svantaggio."),
 'opportunist': ('Scrocco', "Quando la CA o una caratteristica di un nemico che questo Pokémon vede aumenta, la sua aumenta della stessa quantità, per tutta la lotta o per 1 minuto."),
 'orichalcum-pulse': ("Ritmo d'Oricalco", "Con un'azione bonus questo Pokémon porta il sole intenso per 5 round, due volte per riposo breve. Sotto il sole intenso ha vantaggio ai tiri per colpire con FOR o COS come potenza."),
 'poison-puppeteer': ('Malia Tossica', "Quando questo Pokémon avvelena o iper-avvelena qualcuno, lo rende anche affascinato. La creatura può liberarsi dal fascino alla fine di ogni suo turno con un TS su CAR contro la CD di Carisma di questo Pokémon."),
 'primordial-sea': ('Mare Primordiale', "Finché questo Pokémon è in lotta, il tempo è Pioggia Battente e non può cambiare: come la pioggia, ma i danni di tipo Fuoco sono annullati. Se è attiva anche Terra Estrema, il tempo è insieme Sole Estremo e Pioggia Battente."),
 'protosynthesis': ('Paleoattivazione', "FOR e COS di questo Pokémon possono arrivare fino a 22. Sotto il sole intenso ha vantaggio ai TS su FOR e COS."),
 'purifying-salt': ('Sale Purificante', "Questo Pokémon resiste ai danni di tipo Spettro e non può subire stati alterati non volatili."),
 'quark-drive': ('Carica Quark', "DES e SAG di questo Pokémon possono arrivare fino a 22. Sul Campo Elettrico ha vantaggio ai TS su DES e SAG."),
 'rocky-payload': ('Portamassi', "Quando questo Pokémon usa una mossa di tipo Roccia, può tirare i danni due volte e scegliere il totale che preferisce."),
 'seed-sower': ('Spargisemi', "Quando viene colpito da un attacco che fa danni, questo Pokémon può usare la reazione per usare Campo Erboso, anche se non conosce la mossa e senza spendere PP. Fino a tre volte per riposo lungo."),
 'sharpness': ('Affilama', "Le mosse con «taglio», «lama», «fendente», «filo», «spada», «rasoio» o «ascia» nel nome raddoppiano il modificatore MOSSA ai danni."),
 'stalwart': ('Volontà di Ferro', "Questo Pokémon sceglie sempre i suoi bersagli, ignorando gli effetti delle mosse che dirottano gli attacchi."),
 'supersweet-syrup': ('Sciroppo Sublime', "I tiri per colpire contro le creature entro 9 m da questo Pokémon aggiungono 1d4. Non ha effetto sulle creature senza olfatto."),
 'supreme-overlord': ('Generale Supremo', "Questo Pokémon ha +1 ai tiri per colpire per ogni alleato messo KO, fino a un massimo di +5."),
 'sword-of-ruin': ('Spada Nefasta', NEFASTO % 'Costituzione'),
 'tablets-of-ruin': ('Amuleto Nefasto', NEFASTO % 'Forza'),
 'tera-shell': ('Teraguscio', "Finché Terapagos ha i PF al massimo, resiste a tutti i tipi di danno."),
 'tera-shift': ('Teramorfosi', "Terapagos può assumere la Forma Teracristal tante volte al giorno quanto il suo modificatore di COS, con un'azione gratuita. Torna normale dopo 10 minuti o quando vuole."),
 'teraform-zero': ('Zeroformazione', "Finché Terapagos è nella Forma Astrale, tutti gli effetti di campo e di tempo atmosferico entro 300 m finiscono, e non possono essere cambiati."),
 'toxic-chain': ('Catena Tossica', "Quando questo Pokémon colpisce un bersaglio in mischia, il bersaglio effettua un TS su COS con CD 16 o diventa iper-avvelenato."),
 'toxic-debris': ('Mantossina', "Quando subisce danni, questo Pokémon può usare la reazione per spargere punte tossiche: ogni creatura entro 1,5 m effettua un TS su DES con CD pari al livello del Pokémon + 2, e se fallisce è avvelenata."),
 'unseen-fist': ('Pugni Invisibili', "Gli attacchi in mischia di questo Pokémon fanno danni anche attraverso Protezione o Individua."),
 'vessel-of-ruin': ('Vaso Nefasto', NEFASTO % 'Saggezza'),
 'well-baked-body': ('Bentostato', "Questo Pokémon non subisce danni da fuoco o da attacchi di tipo Fuoco: invece la sua CA aumenta di 2 finché non subisce danni o per 1 minuto. Non si cumula."),
 'wind-power': ('Energia Eolica', "Dopo che una mossa di vento lo ha colpito, il numero di dadi di danno del suo prossimo attacco di tipo Elettro raddoppia. Mosse di vento: " + VENTO + "."),
 'wind-rider': ('Vento Propizio', "Questo Pokémon è immune ai danni delle mosse di vento. Inoltre si muove a velocità doppia col vento a favore e dimezzata col vento contro."),
 'zero-to-hero': ('Supercambio', "Quando un alleato non Pokémon di Palafin subisce danni da una fonte che non controlla, Palafin può assumere la Forma Possente: diventa di taglia Media, la CA aumenta di 4, la velocità a piedi diventa 9 m e FOR e DES aumentano di 4 ciascuna (massimo 22). Una volta per riposo lungo; torna normale a fine scontro."),
}
